Clustering Model using K mean and DBscan

This model aims to anwser two questions users may want to find. 

1) KMeans: Which NSW Local Government Areas (LGAs) have similar road crash patterns based on the selected crash features?

2) DBSCAN: Which LGA-year records show unusual crash patterns that do not fit into any identified dense group?

Importing all needed libaries like panda and sklearn

In [1]:
import numpy as np                                   
import pandas as pd                                  
from sklearn.cluster import KMeans, DBSCAN          
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

Load the cleaned dataset

In [2]:
data = pd.read_csv("../data/processed/lga_yearly_aggregates_clustering.csv")
print (data.head())

         LGA  Year  Population  severe_count  non_severe_count  Wet-weather %  \
0     Albury  2020       55466            73                50      12.195122
1   Armidale  2020       29600            47                10      24.561404
2    Ballina  2020       45663            58                19      22.077922
3  Balranald  2020        2257             5                 1       0.000000
4   Bathurst  2020       43444            81                28      23.853211

   Rural-road %  Crash rate per 100k   Severe %  total_crashes
0     13.821138           221.757473  59.349593            123
1     56.140351           192.567568  82.456140             57
2     23.376623           168.626678  75.324675             77
3     83.333333           265.839610  83.333333              6
4     32.110092           250.897707  74.311927            109

In [3]:
#data = data[data["LGA"] != "Unincorporated NSW"]    # remove Unincorporated data for testing ONLY.
print(data.shape)

(645, 10)

Select the columns for the dataset to be used

In [4]:
Dcolumns = ["Crash rate per 100k", "Severe %", "Wet-weather %", "Rural-road %"]
X = data[Dcolumns].values

Scale the values in the dataset so it counts equally.

In [5]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

Creating a table to show scores for s which silhouette data

In [6]:
kmeans_results = []

Test K-Means with 2 to 8 clusters and record the silhouette score for each, to help choose K

In [7]:
# s = silhoutte score which then we will choose our K. In CSV kmeans_k_scores.csv  the column will be saved as k instead of s to avoid confusion
for s in range (2,9):
    range_s = KMeans (n_clusters=s, random_state=20)#K-Means with s clusters (random_state keeps the results repeatable)
    s_labels = range_s.fit_predict(X_scaled)# train it on the scaled data 
    silhouette_avg = silhouette_score(X_scaled,s_labels)
    kmeans_results.append({'k': s,'silhouette_score': silhouette_avg})# store S score in the lsit 
    print(f's = {s}  Silhouette Score: {silhouette_avg:.2f}') # Print score

s = 2  Silhouette Score: 0.30
s = 3  Silhouette Score: 0.31
s = 4  Silhouette Score: 0.28
s = 5  Silhouette Score: 0.29
s = 6  Silhouette Score: 0.29
s = 7  Silhouette Score: 0.25
s = 8  Silhouette Score: 0.27

Train the Kmeans model based on the best/highest silhouette score.

In [8]:
# The highest score is s = 3 (0.31), so K = 3 is used to create and train the model

K=3
model = KMeans(n_clusters = K , random_state=20)
model.fit(X_scaled)

KMeans(n_clusters=3, random_state=20)

Step 7: Evalute Kmeans using Silhoutte score

In [9]:
#first must give every row a clustering number

predictions = model.predict(X_scaled)

# Now must print one score for the whole result
silhouette_avg = silhouette_score(X_scaled, predictions)
print (f'Silhoutte Score:{silhouette_avg:.2f}')

Silhoutte Score:0.31

DBscans part

Apply DBSCAN

In [10]:
dbscan = DBSCAN(eps=1.0, min_samples=5) # set as maximun distance and set at least 5 samples 
dbscan.fit(X_scaled)#Run dbscans

row = dbscan.labels_ # make sure each row is labeled

Evaluating DBSCAN using silhoutte score

In [11]:
silhouette_avg = silhouette_score(X_scaled, row)
print (f'Silhouette Score: {silhouette_avg:.2f}') # decimals form

Silhouette Score: 0.46

Identify the noise in the dataset

In [12]:
noise = np.sum (row ==-1 ) # showing all rows with negative 1
print(f'Number of noise points: {noise}')

Number of noise points: 41

Testing with diffirent values to detemine which eps is better using noise and silhouette value

In [13]:
for eps_try in [0.5, 1.0, 1.5, 2.0]:                                 # try four eps values
    dbscan_try = DBSCAN(eps=eps_try, min_samples=5)                 
    dbscan_try.fit(X_scaled)                                        
    labels_try = dbscan_try.labels_                                  
    silhouette_avg = silhouette_score(X_scaled, labels_try)          # determining thesilhouette score 
    noise = np.sum(labels_try == -1)                               
    print(f'eps = {eps_try}  Silhouette Score: {silhouette_avg:.2f}  Number of noise points: {noise}')

eps = 0.5  Silhouette Score: -0.21  Number of noise points: 276
eps = 1.0  Silhouette Score: 0.46  Number of noise points: 41
eps = 1.5  Silhouette Score: 0.61  Number of noise points: 11
eps = 2.0  Silhouette Score: 0.64  Number of noise points: 9

Table: Clustering sizes and profiles

In [14]:
from IPython.display import display # for borders 

data["kmean data"] = predictions # get values from kmean
data["dbscans data"] = row # adds a group number
display(data["kmean data"].value_counts()) # making sure no cluster is small or hold everything
cluster_avg = data.groupby("kmean data")[Dcolumns].mean().round(2) # getting the average for the data wihtin each cluster
display(cluster_avg)
display(data[Dcolumns].mean().round(2).to_frame("Average")) # create a another box to display the average of each column based on the clusters
display(data["dbscans data"].value_counts())

kmean data
1    335
0    185
2    125
Name: count, dtype: int64

            Crash rate per 100k  Severe %  Wet-weather %  Rural-road %
kmean data
0                        316.00     76.28          11.35         63.73
1                        217.96     67.15          18.42         12.63
2                        433.16     67.95          26.93         67.91

                     Average
Crash rate per 100k   287.78
Severe %               69.92
Wet-weather %          18.04
Rural-road %           38.00

dbscans data
 0    604
-1     41
Name: count, dtype: int64

Identify which LGAs belong to each K-Means cluster based their crash patterns 

Since our K= 3 we will have 3 clusters:

Cluster 0 : Higher rural-road %, highest casualty share, and highest casualty %

In [15]:
cluster0 = data[data["kmean data"] == 0] # finding hte once in clustering 0                # rows in cluster 0
counts0 = cluster0["LGA"].value_counts()
print("Cluster 0: Rural, highest casualty share %, lowest wet-surface %")                # years each LGA spent in cluster 0
print(counts0[counts0 == 5])

Cluster 0: Rural, highest casualty share %, lowest wet-surface %
LGA
Cobar        5
Gunnedah     5
Lachlan      5
Lockhart     5
Narrabri     5
Narromine    5
Name: count, dtype: int64

Cluster 1 :  Mostly non-rural areas and low crash rate

In [16]:
cluster1 = data[data["kmean data"] == 1]                 # rows in cluster 1
counts1 = cluster1["LGA"].value_counts()
print("Cluster 1: Mostly non-rural, low crash rate %")                 # years each LGA spent in cluster 1
print(counts1[counts1 == 5])

Cluster 1: Mostly non-rural, low crash rate %
LGA
Albury                     5
Ballina                    5
Bayside (NSW)              5
Blacktown                  5
Blue Mountains             5
Broken Hill                5
Burwood                    5
Camden                     5
Campbelltown (NSW)         5
Canada Bay                 5
Canterbury-Bankstown       5
Central Coast (NSW)        5
Cessnock                   5
Coffs Harbour              5
Cumberland                 5
Fairfield                  5
Georges River              5
Griffith                   5
Hawkesbury                 5
Hornsby                    5
Hunters Hill               5
Inner West                 5
Kiama                      5
Ku-ring-gai                5
Lake Macquarie             5
Lane Cove                  5
Lismore                    5
Liverpool                  5
Maitland                   5
Mosman                     5
Newcastle                  5
North Sydney               5
Northern Beaches           5
Orange                     5
Parramatta                 5
Penrith                    5
Port Macquarie-Hastings    5
Port Stephens              5
Queanbeyan-Palerang        5
Randwick                   5
Ryde                       5
Shellharbour               5
Shoalhaven                 5
Strathfield                5
Sutherland                 5
Sydney                     5
The Hills                  5
Tweed                      5
Wagga Wagga                5
Waverley                   5
Willoughby                 5
Wollondilly                5
Wollongong                 5
Woollahra                  5
Name: count, dtype: int64

Cluster 2: Rural areas, wet-surface share % and highest crash rate

In [17]:
cluster2 = data[data["kmean data"] == 2]       # rows in cluster 2
counts2 = cluster2["LGA"].value_counts()# years each LGA spent in cluster 2
print("Cluster 2: Rural, highest wet-surface %, highest crash rate % ")
print(counts2[counts2 == 5])

Cluster 2: Rural, highest wet-surface %, highest crash rate %
LGA
Cootamundra-Gundagai    5
Snowy Monaro            5
Snowy Valleys           5
Walcha                  5
Name: count, dtype: int64

Stating the total amount of stable LGAS in each cluster and the total amount of LGAs

In [18]:
print("Cluster 0 stable LGAs:", len(counts0[counts0 == 5]))     
print("Cluster 1 stable LGAs:", len(counts1[counts1 == 5]))     
print("Cluster 2 stable LGAs:", len(counts2[counts2 == 5]))     
print("Total LGAs:", data["LGA"].nunique())

Cluster 0 stable LGAs: 6
Cluster 1 stable LGAs: 54
Cluster 2 stable LGAs: 4
Total LGAs: 129

Which LGAs are unusual? using DBscans

In [19]:
row_noise = data[data["dbscans data"] == -1] # get all the rows labeled as -1
print (row_noise[["LGA", "Year", "Population", "total_crashes"] + Dcolumns + ["kmean data"]]) 
print(row_noise["LGA"].value_counts())# count the total which is flaged per LGA in a year

                      LGA  Year  Population  total_crashes  \
15             Brewarrina  2020        1525              1
24             Carrathool  2020        2892             19
26        Central Darling  2020        1774             19
44              Gilgandra  2020        4327              9
50                 Gwydir  2020        5019             16
71               Lockhart  2020        3308              3
87                 Oberon  2020        5540             31
115                Walcha  2020        3057             21
128    Unincorporated NSW  2020        1055             13
132             Balranald  2021        2208              7
140               Blayney  2021        7511             21
144            Brewarrina  2021        1487              2
153            Carrathool  2021        2873             20
161             Coonamble  2021        3833              5
216                Oberon  2021        5567             37
237           Tenterfield  2021        6800             23
257    Unincorporated NSW  2021        1020             18
261             Balranald  2022        2236              3
266              Berrigan  2022        8712             13
271                 Bogan  2022        2455             14
272                Bourke  2022        2357             17
284       Central Darling  2022        1763             20
318                 Kiama  2022       22983             44
345                Oberon  2022        5590             42
366           Tenterfield  2022        6906             35
371                Uralla  2022        6011             21
373                Walcha  2022        3013             22
375                Warren  2022        2576              7
378                Weddin  2022        3612             14
386    Unincorporated NSW  2022         997             10
390             Balranald  2023        2224              6
401                Bourke  2023        2372             13
413       Central Darling  2023        1764             12
420  Cootamundra-Gundagai  2023       11447             52
499         Upper Lachlan  2023        8726             63
515    Unincorporated NSW  2023        1013             12
519             Balranald  2024        2256              4
624           Tenterfield  2024        7120             48
631                Walcha  2024        2997             17
643           Yass Valley  2024       17555            102
644    Unincorporated NSW  2024         987             15

     Crash rate per 100k    Severe %  Wet-weather %  Rural-road %  kmean data
15             65.573770  100.000000       0.000000      0.000000           0
24            656.984786   73.684211      10.526316    100.000000           0
26           1071.025930   84.210526      36.842105     89.473684           2
44            207.996302  100.000000      11.111111     77.777778           0
50            318.788603   87.500000      25.000000    100.000000           0
71             90.689238   66.666667       0.000000    100.000000           0
87            559.566787   70.967742      45.161290     67.741935           2
115           686.947988   90.476190      33.333333     90.476190           2
128          1232.227488   92.307692       0.000000     84.615385           0
132           317.028986   42.857143      28.571429     85.714286           2
140           279.589935   52.380952      42.857143     57.142857           2
144           134.498991  100.000000      50.000000    100.000000           2
153           696.136443   90.000000      20.000000     90.000000           2
161           130.446126  100.000000      20.000000     80.000000           0
216           664.630860   54.054054      32.432432     70.270270           2
237           338.235294   91.304348      39.130435     60.869565           2
257          1764.705882   94.444444      22.222222    100.000000           2
261           134.168157  100.000000       0.000000     66.666667           0
266           149.219467   46.153846       7.692308     61.538462           1
271           570.264766   50.000000      28.571429     64.285714           2
272           721.255834   82.352941      23.529412     70.588235           2
284          1134.429949   75.000000      30.000000     90.000000           2
318           191.445851   50.000000      38.636364      9.090909           1
345           751.341682   66.666667      30.952381     59.523810           2
366           506.805676   85.714286      28.571429     68.571429           2
371           349.359508   61.904762      47.619048     76.190476           2
373           730.169267   72.727273      40.909091     90.909091           2
375           271.739130  100.000000      42.857143     42.857143           2
378           387.596899   42.857143      14.285714     64.285714           2
386          1003.009027   70.000000       0.000000     90.000000           0
390           269.784173  100.000000      33.333333     50.000000           0
401           548.060708   61.538462       0.000000     53.846154           0
413           680.272109   66.666667       0.000000     58.333333           0
420           454.267494   44.230769      26.923077     67.307692           2
499           721.980289   76.190476      11.111111     85.714286           0
515          1184.600197   66.666667       8.333333     91.666667           2
519           177.304965   50.000000      25.000000     75.000000           2
624           674.157303   79.166667      16.666667     75.000000           2
631           567.233901   70.588235      41.176471     64.705882           2
643           581.031045   53.921569      10.784314     86.274510           2
644          1519.756839   66.666667       0.000000     86.666667           2
LGA
Unincorporated NSW      5
Balranald               4
Central Darling         3
Oberon                  3
Walcha                  3
Tenterfield             3
Brewarrina              2
Carrathool              2
Bourke                  2
Gilgandra               1
Gwydir                  1
Lockhart                1
Blayney                 1
Coonamble               1
Berrigan                1
Bogan                   1
Kiama                   1
Uralla                  1
Warren                  1
Weddin                  1
Cootamundra-Gundagai    1
Upper Lachlan           1
Yass Valley             1
Name: count, dtype: int64

Save all csv for visulisation

In [20]:
import os

# CSV of the complete dataset with K-Means and DBSCAN labels
data.to_csv("../data/processed/lga_clusters.csv", index=False)

# CSV to show the average feature values for each K-Means cluster
cluster_avg.to_csv("../data/processed/cluster_profiles.csv")

# CSV that has k mean silhoutte scores
kmeans_scores = pd.DataFrame(kmeans_results)
kmeans_scores.to_csv("../data/processed/kmeans_k_scores.csv", index=False)

# CSV to compare DBSCAN using eps vlaues to determine how the number of clusters and noise points chnage
epsresults =[]

for eps in [0.5, 1.0, 1.5, 2.0]:
    labels = DBSCAN(eps=eps, min_samples = 5).fit_predict(X_scaled)
    clusters = len (set(labels)- {-1})
    noise = sum(labels == -1)

    epsresults.append([eps, clusters, noise]) #place the results into this box

# Save eps results into a eps
pd.DataFrame(epsresults, columns =["eps", "cluster_count", "noise_count"]).to_csv("../data/processed/dbscan_eps_comparison.csv", index=False)

# CSV for all unusal record
data[data["dbscans data"] == -1].to_csv("../data/processed/dbscan_noise_records.csv", index=False)

Save model for prediction in Assignment 3
 Mainly for the prediction sciprt to load and assign new LGA record to a cluster

In [21]:
import joblib

joblib.dump({
    "scaler": scaler,
    "kmeans": model,
    "features": Dcolumns,
    "cluster_names": 
    {
        0: "Rural, highest casualty share, lowest wet-surface %",
        1: "Mostly non-rural, lowest crash rate",
        2: "Rural, highest wet-surface %, highest crash rate",
    },
}, "../models/kmeans_lga.joblib")

print("Model Saved")

Model Saved